version: "3.8"
name: gpio-db

services:
  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pi-gpio
    ports:
      - 3306:3306
    volumes:
      - gpio-datavolume:/var/lib/mysql
volumes:
  gpio-datavolume:
